### ISSUE TITLE
Write to console if no outputDir provided 

### ISSUE THREAD

**Issue by dmfranko** [webdriverio/wdio-junit-reporter#10]
I believe the the xunit report used to print to the console if an output directory wasn't provided.  That was actually useful for me.  Is there any reason that it can't do that going forward?  Maybe if not doing that by default, but via an option would be good too?

**Comment by christian-bromann** [comment]
@dmfranko we still do that: https://github.com/webdriverio/wdio-junit-reporter/blob/master/lib/reporter.js#L132
