### ISSUE TITLE
reporter generates invalid file name and fails when using appium

### ISSUE THREAD

**Issue by talarari** [webdriverio/wdio-junit-reporter#14]
when setting up webdriver io to work with appium , you have to supply a path to the apk file (for android)

the junit reporter uses the path in the file name and creates a bad name, something like:
8xv7n15b06000308.android.c:\development\someFolder\myapp.apk.xml

i found a workaround to supply outputFileFormat function in the config like this:

```
  reporterOptions: {
    junit: {
        outputDir: './tests',
        outputFileFormat: (x)=> {
               return 'some file name.xml' // or calculate based on x
        }
    }
},
```

**Comment by christian-bromann** [comment]
Yup, that's for what `outputFileFormat` is for 👍
