### ISSUE TITLE
xUnit reporter produces file names in an invalid format

### ISSUE THREAD

**Issue by monolithed** [webdriverio/wdio-junit-reporter#19]
<img width="652" alt="707010499dda939536fd6c54d596b004" src="https://cloud.githubusercontent.com/assets/803674/19393756/c8992cc2-923e-11e6-9d02-6bd713f08c54.png">

XUnit files that the reporter produces are identical due to invisible UTF characters.

**Comment by christian-bromann** [comment]
This should be fixed with the latest version of WebdriverIO
