### ISSUE TITLE
Test & Suite names have appended integers

### ISSUE THREAD

**Issue by DylanLacey** [webdriverio/wdio-junit-reporter#22]
In at least two environments, the suite and test names have appended integers:

    <testcase classname="chrome.webdriver.io page2" name="should have the right title - the fancy generator way3" time="3.666">

instead of 

    <testcase classname="chrome.webdriver.io page" name="should have the right title - the fancy generator way" time="3.666">

This is a bit wacky and also causes the Sauce Labs Jenkins Plugin to incorrectly parse the results, preventing it from setting result status correctly.

Attached is a full example of a broken file (extension changed to prevent GitHub being unhappy):
[WDIO.xunitchrome.0-0.txt](https://github.com/webdriverio/wdio-junit-reporter/files/686331/WDIO.xunitchrome.0-0.txt)

**Comment by nilols** [comment]
One problem with the reporter is that it uses a object key `suiteName` as the testsuite name, e.g.
```js
for (let suiteName of Object.keys(spec.suites)) {
    const suite = spec.suites[suiteName]
    const testSuite = builder.testSuite()
        .name(suiteName.toLowerCase().split(/[^a-z0-9]+/).filter((item) => item && item.length).join('_'))
```
instead of
```js
for (let suiteName of Object.keys(spec.suites)) {
    const suite = spec.suites[suiteName]
    const testSuite = builder.testSuite()
        .name(suite.title.toLowerCase().split(/[^a-z0-9]+/).filter((item) => item && item.length).join('_'))
```
Think you should rename `suiteName` to `suiteId` or `suiteKey` and then use the data from the suite
```js
for (let suiteKey of Object.keys(spec.suites)) {
    const suite = spec.suites[suiteKey]
    const suiteName = suite.title.toLowerCase().split(/[^a-z0-9]+/).filter((item) => item && item.length).join('_')
    const testSuite = builder.testSuite()
        .name(suiteName)
```
the testcase part have the same issue, also resulting in numbers in the names.

**Comment by nilols** [comment]
To clarify it a bit the `spec.suites` keys need to be unique, thereof the numbers, but as described above the problem is that the keys is used as names

**Comment by nilols** [comment]
Created a PR with a suggestion for a fix, please comment

**Comment by nilols** [comment]
@christian-bromann can you have a look at this and see if it's ok to merge?

**Comment by christian-bromann** [comment]
@nilols yes, let's continue convo in #24
