### ISSUE TITLE
Test class name as part of outputFileFormat opts

### ISSUE THREAD

**Issue by kaushlakers** [webdriverio/wdio-junit-reporter#32]
**Currently**: According to the readme, there is an option to customize the output file format. The options available to customize this is just the runner id and the capabilities. These are not very readable. 

Would you entertain the possibility of making more details about the test available while specifying the test file format? 

Ideally it would be nice to have the test class name, so that we can include it in the name. 

If this sounds reasonable, then I can make the change and send a PR with some guidance. :)

**Comment by christian-bromann** [comment]
Please do , thanks

**Comment by kaushlakers** [comment]
@christian-bromann can I get some guidance on what I need to change for this? I see the config passed into the function on this line. Shouldn't the test class names already be accessible then? https://github.com/kaushlakers/wdio-junit-reporter/blob/master/lib/reporter.js#L135

**Comment by kaushlakers** [comment]
What do you think is reasonable to expose? I just realized I can customize quite easily for my use case, where I need just the suite name, since the reporter generates 1 file per suite.

**Comment by christian-bromann** [comment]
Not sure which data is available to you?

**Comment by kaushlakers** [comment]
I found a work around for my specific use case and I don't think it makes sense to push that change here. Closing this. Thanks! 😄
