### ISSUE TITLE
Unable to pass testcase name regular expression 

### ISSUE THREAD

**Issue by prakashomp** [webdriverio/wdio-junit-reporter#44]
Hi,

I am passing reporter options as below

reporters: ['dot', 'junit'],
    reporterOptions: {
        junit: {
            outputDir: './reporter',
            suiteNameFormat:'/[^a-z0-9A-Z :; *]+/'
        }
    }
But it is not working 
I want test case name as like as test case  

Regards
OmPrakash

**Comment by christian-bromann** [comment]
@prakashomp are you using latest package version?

**Comment by prakashomp** [comment]
Yes,I am using latest package version.

**Comment by prakashomp** [comment]
@christian-bromann ,
here suiteNameFormat is not working.
Do we have any method to set xml file name as test name?

**Comment by christian-bromann** [comment]
use the `outputFileFormat` option like in the example in the [README.md](https://github.com/webdriverio/wdio-junit-reporter#outputfileformat)
