### ISSUE TITLE
version 0.3.1 not released (crash fix)

### ISSUE THREAD

**Issue by Kignuf** [webdriverio/wdio-junit-reporter#71]
Hello,

A couple weeks ago I made a PR to fix a crash that occured when using this reporter combined to a project that has cucumber hooks. The PR was accepted but the release was never published.

Was it forgotten, or is there something preventing to publish the fix ?

Thanks.

**Comment by christian-bromann** [comment]
We will publish this new version soon. I have just been to busy recently. Sorry.
