### ISSUE TITLE
Suite/test are always lowercase in test reports

### ISSUE THREAD

**Issue by patthiel** [webdriverio/wdio-junit-reporter#80]
When we upgraded from 0.2.0 to 0.3.1 we noticed in our test reports that the test names went from "should Test this Thing in Here" to all lower case "should test this thing in here".

We find this an issue because we use capital letters to facilitate formatting some of our test names (perhaps this is non-standard, but it's the way we've chosen to do it).

I have a patch that could be applied to fix that removes the toLowerCase being called on suites/tests and would have to modify the default suite name regex.

I'll push up a PR with a unit test shortly if there is no opposition to this. cc @christian-bromann

**Comment by mcelotti** [comment]
Hi patthiel, if @christian-bromann has no objection I can make the PR for the current version (0.4.0)

**Comment by christian-bromann** [comment]
I have not strong opinion on this, so if you guys find it annoying, feel free to shoot a PR

**Comment by mcelotti** [comment]
Ok, since there's no special reason for being lowercase I'll create the PR

**Comment by ianrenauld** [comment]
Something went wrong with this PR, as all uppercase letters are now disappearing (at least for me). See #91

**Comment by patthiel** [comment]
Sorry guys, somehow i missed this communication. @mcelotti thanks for PR'ing!

**Comment by christian-bromann** [comment]
I will close this then!
