### ISSUE TITLE
Combine test suites and create a single xml file

### ISSUE THREAD

**Issue by mcelotti** [webdriverio/wdio-junit-reporter#87]
Hi, is it possible to get a single xml file that combines the results of many test suites instead of many xml files?

**Comment by christian-bromann** [comment]
This is right now not possible, every test creates its own xml file. Why do you need to have one file? It works perfectly in Jenkins. Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by mcelotti** [comment]
Hi Christian, thanks for the answer, I thought you could label this as a question since having a single file is fundamental for junit xray import (https://confluence.xpand-addons.com/display/XRAY/Import+Execution+Results+-+REST#ImportExecutionResults-REST-JUnitXMLresults).
Anyway I'll take a look at the xml creation, maybe I can figure out something on my own, if I find a solution I'll update this issue so that other people can take advantage of it.
Thank you.

**Comment by christian-bromann** [comment]
@mcelotti feel free to propose a PR that bundles all XML files into one so it works with XRAY, we might can have an option for it so people can choose whether or not to bundle it.

**Comment by mcelotti** [comment]
Ok, I'll take a look to make this configurable so we can have both options
