### ISSUE TITLE
xUnit reporter produces files in an invalid format

### ISSUE THREAD

**Issue by charliedavison** [webdriverio/wdio-junit-reporter#9]
I'm working on integrating some tests that make use of webdriverio and the XUnit reporter into my visual studio online build process, but the XUnit files that the reporter produces are throwing a build error saying they are invalid format. 

Please see the error below:

> 2016-02-08T17:53:52.4196961Z Executing the powershell script: C:\TfsBuildAgents\G2TFS-VSO-BuildAgent\tasks\PublishTestResults\1.0.18\PublishTestResults.ps1
> 2016-02-08T17:53:52.5758710Z Publishing Test Results...
> 2016-02-08T17:53:53.8326758Z ##[warning]Invalid results file. Make sure the Test Result Format field in the task matches the result format of the file: 'C:\TfsBuildAgents\VSO-BuildAgent_work\2\s\WDIO.xunit.chrome.2672.xml'

The file produced was(Renamed to .txt for upload to github):

[WDIO.xunit.chrome.2672.txt](https://github.com/webdriverio/wdio-junit-reporter/files/121998/WDIO.xunit.chrome.2672.txt)

**Comment by dajester2013** [comment]
I'm also not able to load the JUnit files in Eclipse due to invalid unicode characters:

![image](https://cloud.githubusercontent.com/assets/4575960/16392084/b3886372-3c6f-11e6-8493-ae637979b877.png)

**Comment by christian-bromann** [comment]
This got fixed with latest version `v0.3.0`
