### ISSUE TITLE
Uppercase letters in test case name are causing missing letters from test case name in the JUnit report

### ISSUE THREAD

**Issue by ianrenauld** [webdriverio/wdio-junit-reporter#91]
My test name is "Shopping Page Is Displayed Test", which is correctly displayed in Spec reporter, but since today (so I assume with release v0.4.1 of wdio-junit-reporter), I get this in the JUnit report: "hopping_age_s_isplayed_est".

Both the classname and name of the < testcase > tag are affected.

If I change the title to "Shopping Page Is DisPlayed Test" then I get "hopping_age_s_is_layed_est" which is all kinds of wrong!

**Comment by christian-bromann** [comment]
@ianrenauld can you provide the xml reports or anything that helps us to look into the issue. Also PRs with fixes are much appreciated 😉

**Comment by patthiel** [comment]
I'm seeing the same issue, but are we sure this isn't an issue with the jenkins junit plugin? my test report xml file displays all the information correctly

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="homepage_suite_smoke_suite" timestamp="2018-03-07T14:20:43" time="1.337" tests="4" failures="0" errors="0" skipped="1">
    <properties>
      <property name="specId" value="1c6ba07a7d25d357fb1334052acc4ce9"/>
      <property name="suiteName" value="Homepage Suite Smoke Suite"/>
      <property name="capabilities" value="chrome"/>
      <property name="file" value="./test/specs/homepage/smoke-homepage.spec.js"/>
    </properties>
    <testcase classname="chrome.homepage_suite_smoke_suite" name="should_display_base_page_elements" time="0.234"/>
    <testcase classname="chrome.homepage_suite_smoke_suite" name="should_display_recent_questions" time="0.077"/>
    <testcase classname="chrome.homepage_suite_smoke_suite" name="should_display_search_elements" time="0.11"/>
    <testcase classname="chrome.homepage_suite_smoke_suite" name="should_display_pagination" time="0.089"/>
    <testcase classname="chrome.homepage_suite_smoke_suite" name="skipped_test" time="0.001">
      <skipped/>
    </testcase>
  </testsuite>
</testsuites>
```

**Comment by ianrenauld** [comment]
I've attached my XML report. This was a local run (not through Jenkins, although I see the same on Jenkins). I'm running both the Spec and the JUnit reporter at the same time, just in case this has an impact.

[WDIO.xunit.chrome.0-0.xml.zip](https://github.com/webdriverio/wdio-junit-reporter/files/1789494/WDIO.xunit.chrome.0-0.xml.zip)

**Comment by christian-bromann** [comment]
Fixed issue and will release it as `v0.4.2`

**Comment by ianrenauld** [comment]
Thanks for the super fast service, as always, @christian-bromann !

**Comment by patthiel** [comment]
Cheers @christian-bromann
