### ISSUE TITLE
Missing lodash dependency in package.json.

### ISSUE THREAD

**Issue by bryanatibm** [webdriverio/wdio-junit-reporter#96]
This project should specify it's lodash dependency in package.json.  The project I am using this on is using an older version of lodash, so the get() function call was failing (project is using lodash 2.4.2).  In order to get around this, had to shrinkwrap the project and override the dependencies for wdio-junit-reporter to add in lodash ~ 4.0 as a requirement.  This got around the issue, but it would be simpler if wdio-junit-reporter had the lodash dependency specified :).

**Comment by christian-bromann** [comment]
Fix release in `0.4.3`
